//Author: Mayank Jain
//Description: This program decrypts the txt file using pseudo random numbers created by the class Randomize
//------------It moves each character back by the same numbers generated by the Randomize class using the same key used to encypt

import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;


public class Decrypt {
	
	public static void main(String[] args){
		Scanner stdin = new Scanner(System.in);
		
		String myFileName = "output.txt";
		
		String outputFileName = "decrypted.txt";
		
		
		try{
			FileReader myFile = new FileReader(myFileName);
			Scanner scanMyFile = new Scanner(myFile);
			PrintWriter output = new PrintWriter(new FileWriter(outputFileName));
			//Reading the encrypted file
			String sentence = "";
			while(scanMyFile.hasNextLine())
				sentence += scanMyFile.next() + " ";
		
			//Array of all characters
			String alpha="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*()_+{}:<>?[];,./ ";
			String[] alphaArray = alpha.split("");

			//Creating an array of characters that we want to decrypt
			String[] arrayToDecrypt = sentence.split("");
			String[] DecryptedArray = new String[arrayToDecrypt.length];
			
			System.out.println("-------------");
			System.out.println("Welcome to Secure Vault. This program will decrypt your text.");
			System.out.print("Enter your same key to decrypt the text (<9 digit): ");
			long code = stdin.nextInt();
			
			//Creating a randomizer with the same key to shift the characters backwards in the same way
			Randomize k = new Randomize(code,6);
			
			System.out.println("Performing Encryption");
			for(int i=0;i<arrayToDecrypt.length-1;i++){
				for(int j=0;j<alphaArray.length;j++){
					
					 if(arrayToDecrypt[i].equals(alphaArray[j])){	
						 	 code = k.getIt();	//fetches the next random number
							 DecryptedArray[i] = alphaArray[(int) Math.floorMod(j-code, alpha.length())];//shifts back the character
							 
							 output.print(DecryptedArray[i]); //prints it in the decrypted file
							 break; //goes to next character since done
					}
					
				}
				
			}
		stdin.close();
		scanMyFile.close();
		output.close();
		}
		catch(Exception ex){
			System.out.println("exception: "+ex.getMessage()+" caught");
		}	
	
		/*
		
		try{
			FileReader myFile = new FileReader(myFileName);
			Scanner scanMyFile = new Scanner(myFile);
			PrintWriter output = new PrintWriter(new FileWriter(outputFileName));
			
		}
		catch(Exception ex){
			System.out.println("exception: "+ex.getMessage()+"caught");
		}	
*/
	}
}
